# Configuración exacta según repositorio funcional
---
include:
  - board: seeeduino_xiao_ble
    shield: totem_dongle prospector_adapter
  - board: seeeduino_xiao_ble
    shield: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right